# disabled
name: Build Image
on: push
    
permissions:
  contents: write
jobs:
 blastpad-image:
    runs-on: ubuntu-latest
    steps:
      - run: |
            mkdir -p blastpad-stage/package-test && {
            cat > blastpad-stage/package-test/00-run.sh <<-EOF
            #!/bin/bash

            apt-get install -y curl
            curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
            apt install git-all -y
            git clone https://github.com/Capstone-Projects-2024-Spring/project-blastpad

            cd project-blastpad/install
            ./dependencies.sh
            cd ../..
            cp -r project-blastpad "${ROOTFS_DIR}/home/blastpad"
            
            adduser ${FIRST_USER_NAME} blastpad
            chown -R blastpad "${ROOTFS_DIR}/home/blastpad"

            EOF
            } &&
            chmod +x blastpad-stage/package-test/00-run.sh &&
            echo "nodejs" >> blastpad-stage/package-test/01-packages &&
            echo "git" >> blastpad-stage/package-test/01-packages &&
            {
            cat > blastpad-stage/prerun.sh <<-EOF
            #!/bin/bash -e
            if [ ! -d "\${ROOTFS_DIR}" ]; then
            copy_previous
            fi
            EOF
            } && chmod +x blastpad-stage/prerun.sh


      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          enable-ssh: 1
          keyboard-layout: English (US)
          keyboard-keymap: us
          image-name: test
          disable-first-boot-user-rename: 1
          password: blastpad
          username: blastpad
          stage-list: stage0 ./blastpad-stage
          verbose-output: true

      - uses: actions/upload-artifact@v3
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}