# disabled
name: Build Image
on: push
    
permissions:
  contents: write
jobs:
  blastpad-image:
    runs-on: ubuntu-latest
    steps:
      # Create a stage 'blastpad-stage' instructing to add Nodesource repo and install nodejs as dependency
      - run: |
            mkdir -p blastpad-stage/package-test && {
            cat > blastpad-stage/package-test/00-run-chroot.sh <<-EOF
            #!/bin/bash
            # apt-get install -y curl
            apt install git-all -y
            HOME="${ROOTFS_DIR}/home/${FIRST_USER_NAME}"
            git clone https://github.com/Capstone-Projects-2024-Spring/project-blastpad
            cd project-blastpad/install
            ./dependencies.sh
            cd ../..
            cp -r project-blastpad "${HOME}/"
            EOF
            } &&
            chmod +x blastpad-stage/package-test/00-run-chroot.sh &&
            echo "nodejs" > blastpad-stage/package-test/01-packages &&
            {
            cat > blastpad-stage/prerun.sh <<-EOF
            #!/bin/bash -e
            if [ ! -d "\${ROOTFS_DIR}" ]; then
            copy_previous
            fi
            EOF
            } && chmod +x blastpad-stage/prerun.sh

      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          enable-ssh: 1
          keyboard-layout: English (US)
          keyboard-keymap: us
          image-name: test
          disable-first-boot-user-rename: 1
          password: blastpad
          username: blastpad
          stage-list: stage0 stage1 stage2 stage3 ./blastpad-stage

      - uses: actions/upload-artifact@v3
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}