# disabled
name: Build Image
on: push
    
permissions:
  contents: write
jobs:
 blastpad-image:
    runs-on: ubuntu-latest
    steps:
      - run: |
            curl -L https://github.com/Capstone-Projects-2024-Spring/project-blastpad/tarball/BP-186-Versioned-Blastpad-Image-split-l8r | tar zx
            mv Capstone-Projects*/install/test-stage blastpad-stage

      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          enable-ssh: 1
          keyboard-layout: English (US)
          keyboard-keymap: us
          image-name: test
          disable-first-boot-user-rename: 1
          password: blastpad
          username: blastpad
          stage-list: stage0 stage1 stage2 ./blastpad-stage
          verbose-output: false

      - uses: actions/upload-artifact@v3
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}