# disabled
name: Build Image
on: push
    
permissions:
  contents: write
jobs:
  blastpad-image:
    runs-on: ubuntu-latest
    steps:
      - run: |
            mkdir -p blastpad-stage/package-test && {
            cat > blastpad-stage/package-test/00-run-chroot.sh <<-EOF
            #!/bin/bash
            apt-get install -y curl
            curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
            apt install git-all -y
            git clone https://github.com/Capstone-Projects-2024-Spring/project-blastpad
            touch git_test
            cd project-blastpad/install
            ./dependencies.sh
            cd ../..
            cp -r project-blastpad "${ROOTFS_DIR}/home/blastpad"
            cd "${ROOTFS_DIR}/home/blastpad"
            touch userdir_test
            EOF
            } &&
            chmod +x blastpad-stage/package-test/00-run-chroot.sh &&
            echo "nodejs" > blastpad-stage/package-test/01-packages &&
            echo "git" > blastpad-stage/package-test/01-packages &&
            echo "python3-pip" > blastpad-stage/package-test/01-packages &&
            echo "python3-flask" > blastpad-stage/package-test/01-packages &&
            echo "python3-dev" > blastpad-stage/package-test/01-packages &&
            echo "python3-pillow" > blastpad-stage/package-test/01-packages &&
            echo "python3-pil.imagetk" > blastpad-stage/package-test/01-packages &&
            echo "python3-pygame" > blastpad-stage/package-test/01-packages &&
            echo "python3-pgzero" > blastpad-stage/package-test/01-packages &&
            echo "python3-tk" > blastpad-stage/package-test/01-packages &&
            {
            cat > blastpad-stage/prerun.sh <<-EOF
            #!/bin/bash -e
            if [ ! -d "\${ROOTFS_DIR}" ]; then
            copy_previous
            fi
            EOF
            } && chmod +x blastpad-stage/prerun.sh

      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          enable-ssh: 1
          keyboard-layout: English (US)
          keyboard-keymap: us
          image-name: test
          disable-first-boot-user-rename: 1
          password: blastpad
          username: blastpad
          stage-list: stage0 stage1 ./blastpad-stage

      - uses: actions/upload-artifact@v3
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}