# disabled
on:
    push:
        paths:
          - blockly/**

permissions:
  contents: write

jobs:
  webpack:
    name: Blockly Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: cd blockly && npm install && npm run build

    # - name: Configure Git
    #   run: |
    #     git config user.name "GitHub Actions Bot"
    #     git config user.email "<>"

    # - name: Commit Build
    #   run: |
    #     git add --all
    #     git commit -m "Webpack Production Build"
    #     git push origin main